// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HousingSite.proto

package com.group5;

public interface GetUserByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.GetUserByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
