// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HousingSite.proto

package com.group5;

public interface ListingFiltersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.ListingFiltersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 postNumber = 1;</code>
   * @return The postNumber.
   */
  long getPostNumber();

  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The imageBase64Data.
   */
  java.lang.String getImageBase64Data();
  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The bytes for imageBase64Data.
   */
  com.google.protobuf.ByteString
      getImageBase64DataBytes();

  /**
   * <code>string imageContentType = 3;</code>
   * @return The imageContentType.
   */
  java.lang.String getImageContentType();
  /**
   * <code>string imageContentType = 3;</code>
   * @return The bytes for imageContentType.
   */
  com.google.protobuf.ByteString
      getImageContentTypeBytes();

  /**
   * <code>string imageFileName = 4;</code>
   * @return The imageFileName.
   */
  java.lang.String getImageFileName();
  /**
   * <code>string imageFileName = 4;</code>
   * @return The bytes for imageFileName.
   */
  com.google.protobuf.ByteString
      getImageFileNameBytes();
}
