// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HousingSite.proto

package com.group5;

public interface ListingFiltersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.ListingFiltersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 postNumber = 1;</code>
   * @return Whether the postNumber field is set.
   */
  boolean hasPostNumber();
  /**
   * <code>optional int64 postNumber = 1;</code>
   * @return The postNumber.
   */
  long getPostNumber();

  /**
   * <code>optional int64 maxPrice = 2;</code>
   * @return Whether the maxPrice field is set.
   */
  boolean hasMaxPrice();
  /**
   * <code>optional int64 maxPrice = 2;</code>
   * @return The maxPrice.
   */
  long getMaxPrice();

  /**
   * <code>optional int64 minArea = 3;</code>
   * @return Whether the minArea field is set.
   */
  boolean hasMinArea();
  /**
   * <code>optional int64 minArea = 3;</code>
   * @return The minArea.
   */
  long getMinArea();
}
