// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.group5.proto.User;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.User.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isValid = 1;</code>
   * @return The isValid.
   */
  boolean getIsValid();
}
