// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.group5.proto.User;

public interface LoginInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.User.LoginInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
