// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

/**
 * Protobuf type {@code com.group5.proto.Listing.CreateHouseListingRequest}
 */
public final class CreateHouseListingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.group5.proto.Listing.CreateHouseListingRequest)
    CreateHouseListingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateHouseListingRequest.newBuilder() to construct.
  private CreateHouseListingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateHouseListingRequest() {
    images_ = java.util.Collections.emptyList();
    userEmail_ = "";
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateHouseListingRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateHouseListingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.group5.proto.Listing.AddressMessage.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(com.group5.proto.Listing.AddressMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            constructionYear_ = input.readInt32();
            break;
          }
          case 24: {

            lastRebuilt_ = input.readInt32();
            break;
          }
          case 32: {

            hasInspection_ = input.readBool();
            break;
          }
          case 41: {

            groundArea_ = input.readDouble();
            break;
          }
          case 49: {

            floorArea_ = input.readDouble();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              images_ = new java.util.ArrayList<com.group5.proto.Listing.ImageFileMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            images_.add(
                input.readMessage(com.group5.proto.Listing.ImageFileMessage.parser(), extensionRegistry));
            break;
          }
          case 65: {

            price_ = input.readDouble();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            userEmail_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        images_ = java.util.Collections.unmodifiableList(images_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.group5.proto.Listing.CreateHouseListingRequest.class, com.group5.proto.Listing.CreateHouseListingRequest.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private com.group5.proto.Listing.AddressMessage address_;
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public com.group5.proto.Listing.AddressMessage getAddress() {
    return address_ == null ? com.group5.proto.Listing.AddressMessage.getDefaultInstance() : address_;
  }
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   */
  @java.lang.Override
  public com.group5.proto.Listing.AddressMessageOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int CONSTRUCTIONYEAR_FIELD_NUMBER = 2;
  private int constructionYear_;
  /**
   * <code>int32 constructionYear = 2;</code>
   * @return The constructionYear.
   */
  @java.lang.Override
  public int getConstructionYear() {
    return constructionYear_;
  }

  public static final int LASTREBUILT_FIELD_NUMBER = 3;
  private int lastRebuilt_;
  /**
   * <code>int32 lastRebuilt = 3;</code>
   * @return The lastRebuilt.
   */
  @java.lang.Override
  public int getLastRebuilt() {
    return lastRebuilt_;
  }

  public static final int HASINSPECTION_FIELD_NUMBER = 4;
  private boolean hasInspection_;
  /**
   * <code>bool hasInspection = 4;</code>
   * @return The hasInspection.
   */
  @java.lang.Override
  public boolean getHasInspection() {
    return hasInspection_;
  }

  public static final int GROUNDAREA_FIELD_NUMBER = 5;
  private double groundArea_;
  /**
   * <code>double groundArea = 5;</code>
   * @return The groundArea.
   */
  @java.lang.Override
  public double getGroundArea() {
    return groundArea_;
  }

  public static final int FLOORAREA_FIELD_NUMBER = 6;
  private double floorArea_;
  /**
   * <code>double floorArea = 6;</code>
   * @return The floorArea.
   */
  @java.lang.Override
  public double getFloorArea() {
    return floorArea_;
  }

  public static final int IMAGES_FIELD_NUMBER = 7;
  private java.util.List<com.group5.proto.Listing.ImageFileMessage> images_;
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.group5.proto.Listing.ImageFileMessage> getImagesList() {
    return images_;
  }
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.group5.proto.Listing.ImageFileMessageOrBuilder> 
      getImagesOrBuilderList() {
    return images_;
  }
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  @java.lang.Override
  public int getImagesCount() {
    return images_.size();
  }
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  @java.lang.Override
  public com.group5.proto.Listing.ImageFileMessage getImages(int index) {
    return images_.get(index);
  }
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  @java.lang.Override
  public com.group5.proto.Listing.ImageFileMessageOrBuilder getImagesOrBuilder(
      int index) {
    return images_.get(index);
  }

  public static final int PRICE_FIELD_NUMBER = 8;
  private double price_;
  /**
   * <code>double price = 8;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int USEREMAIL_FIELD_NUMBER = 9;
  private volatile java.lang.Object userEmail_;
  /**
   * <code>string userEmail = 9;</code>
   * @return The userEmail.
   */
  @java.lang.Override
  public java.lang.String getUserEmail() {
    java.lang.Object ref = userEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string userEmail = 9;</code>
   * @return The bytes for userEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserEmailBytes() {
    java.lang.Object ref = userEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 10;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 10;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 10;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != null) {
      output.writeMessage(1, getAddress());
    }
    if (constructionYear_ != 0) {
      output.writeInt32(2, constructionYear_);
    }
    if (lastRebuilt_ != 0) {
      output.writeInt32(3, lastRebuilt_);
    }
    if (hasInspection_ != false) {
      output.writeBool(4, hasInspection_);
    }
    if (java.lang.Double.doubleToRawLongBits(groundArea_) != 0) {
      output.writeDouble(5, groundArea_);
    }
    if (java.lang.Double.doubleToRawLongBits(floorArea_) != 0) {
      output.writeDouble(6, floorArea_);
    }
    for (int i = 0; i < images_.size(); i++) {
      output.writeMessage(7, images_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(8, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, description_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddress());
    }
    if (constructionYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, constructionYear_);
    }
    if (lastRebuilt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lastRebuilt_);
    }
    if (hasInspection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, hasInspection_);
    }
    if (java.lang.Double.doubleToRawLongBits(groundArea_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, groundArea_);
    }
    if (java.lang.Double.doubleToRawLongBits(floorArea_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, floorArea_);
    }
    for (int i = 0; i < images_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, images_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, description_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.group5.proto.Listing.CreateHouseListingRequest)) {
      return super.equals(obj);
    }
    com.group5.proto.Listing.CreateHouseListingRequest other = (com.group5.proto.Listing.CreateHouseListingRequest) obj;

    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (getConstructionYear()
        != other.getConstructionYear()) return false;
    if (getLastRebuilt()
        != other.getLastRebuilt()) return false;
    if (getHasInspection()
        != other.getHasInspection()) return false;
    if (java.lang.Double.doubleToLongBits(getGroundArea())
        != java.lang.Double.doubleToLongBits(
            other.getGroundArea())) return false;
    if (java.lang.Double.doubleToLongBits(getFloorArea())
        != java.lang.Double.doubleToLongBits(
            other.getFloorArea())) return false;
    if (!getImagesList()
        .equals(other.getImagesList())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getUserEmail()
        .equals(other.getUserEmail())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + CONSTRUCTIONYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getConstructionYear();
    hash = (37 * hash) + LASTREBUILT_FIELD_NUMBER;
    hash = (53 * hash) + getLastRebuilt();
    hash = (37 * hash) + HASINSPECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasInspection());
    hash = (37 * hash) + GROUNDAREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getGroundArea()));
    hash = (37 * hash) + FLOORAREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFloorArea()));
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getUserEmail().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.CreateHouseListingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.group5.proto.Listing.CreateHouseListingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.group5.proto.Listing.CreateHouseListingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.group5.proto.Listing.CreateHouseListingRequest)
      com.group5.proto.Listing.CreateHouseListingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.group5.proto.Listing.CreateHouseListingRequest.class, com.group5.proto.Listing.CreateHouseListingRequest.Builder.class);
    }

    // Construct using com.group5.proto.Listing.CreateHouseListingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      constructionYear_ = 0;

      lastRebuilt_ = 0;

      hasInspection_ = false;

      groundArea_ = 0D;

      floorArea_ = 0D;

      if (imagesBuilder_ == null) {
        images_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imagesBuilder_.clear();
      }
      price_ = 0D;

      userEmail_ = "";

      description_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
    }

    @java.lang.Override
    public com.group5.proto.Listing.CreateHouseListingRequest getDefaultInstanceForType() {
      return com.group5.proto.Listing.CreateHouseListingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.group5.proto.Listing.CreateHouseListingRequest build() {
      com.group5.proto.Listing.CreateHouseListingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.group5.proto.Listing.CreateHouseListingRequest buildPartial() {
      com.group5.proto.Listing.CreateHouseListingRequest result = new com.group5.proto.Listing.CreateHouseListingRequest(this);
      int from_bitField0_ = bitField0_;
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.constructionYear_ = constructionYear_;
      result.lastRebuilt_ = lastRebuilt_;
      result.hasInspection_ = hasInspection_;
      result.groundArea_ = groundArea_;
      result.floorArea_ = floorArea_;
      if (imagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          images_ = java.util.Collections.unmodifiableList(images_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.images_ = images_;
      } else {
        result.images_ = imagesBuilder_.build();
      }
      result.price_ = price_;
      result.userEmail_ = userEmail_;
      result.description_ = description_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.group5.proto.Listing.CreateHouseListingRequest) {
        return mergeFrom((com.group5.proto.Listing.CreateHouseListingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.group5.proto.Listing.CreateHouseListingRequest other) {
      if (other == com.group5.proto.Listing.CreateHouseListingRequest.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.getConstructionYear() != 0) {
        setConstructionYear(other.getConstructionYear());
      }
      if (other.getLastRebuilt() != 0) {
        setLastRebuilt(other.getLastRebuilt());
      }
      if (other.getHasInspection() != false) {
        setHasInspection(other.getHasInspection());
      }
      if (other.getGroundArea() != 0D) {
        setGroundArea(other.getGroundArea());
      }
      if (other.getFloorArea() != 0D) {
        setFloorArea(other.getFloorArea());
      }
      if (imagesBuilder_ == null) {
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
      } else {
        if (!other.images_.isEmpty()) {
          if (imagesBuilder_.isEmpty()) {
            imagesBuilder_.dispose();
            imagesBuilder_ = null;
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImagesFieldBuilder() : null;
          } else {
            imagesBuilder_.addAllMessages(other.images_);
          }
        }
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getUserEmail().isEmpty()) {
        userEmail_ = other.userEmail_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.group5.proto.Listing.CreateHouseListingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.group5.proto.Listing.CreateHouseListingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.group5.proto.Listing.AddressMessage address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.group5.proto.Listing.AddressMessage, com.group5.proto.Listing.AddressMessage.Builder, com.group5.proto.Listing.AddressMessageOrBuilder> addressBuilder_;
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     * @return The address.
     */
    public com.group5.proto.Listing.AddressMessage getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.group5.proto.Listing.AddressMessage.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public Builder setAddress(com.group5.proto.Listing.AddressMessage value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public Builder setAddress(
        com.group5.proto.Listing.AddressMessage.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public Builder mergeAddress(com.group5.proto.Listing.AddressMessage value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            com.group5.proto.Listing.AddressMessage.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public com.group5.proto.Listing.AddressMessage.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    public com.group5.proto.Listing.AddressMessageOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            com.group5.proto.Listing.AddressMessage.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.group5.proto.Listing.AddressMessage, com.group5.proto.Listing.AddressMessage.Builder, com.group5.proto.Listing.AddressMessageOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.group5.proto.Listing.AddressMessage, com.group5.proto.Listing.AddressMessage.Builder, com.group5.proto.Listing.AddressMessageOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private int constructionYear_ ;
    /**
     * <code>int32 constructionYear = 2;</code>
     * @return The constructionYear.
     */
    @java.lang.Override
    public int getConstructionYear() {
      return constructionYear_;
    }
    /**
     * <code>int32 constructionYear = 2;</code>
     * @param value The constructionYear to set.
     * @return This builder for chaining.
     */
    public Builder setConstructionYear(int value) {
      
      constructionYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 constructionYear = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConstructionYear() {
      
      constructionYear_ = 0;
      onChanged();
      return this;
    }

    private int lastRebuilt_ ;
    /**
     * <code>int32 lastRebuilt = 3;</code>
     * @return The lastRebuilt.
     */
    @java.lang.Override
    public int getLastRebuilt() {
      return lastRebuilt_;
    }
    /**
     * <code>int32 lastRebuilt = 3;</code>
     * @param value The lastRebuilt to set.
     * @return This builder for chaining.
     */
    public Builder setLastRebuilt(int value) {
      
      lastRebuilt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastRebuilt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastRebuilt() {
      
      lastRebuilt_ = 0;
      onChanged();
      return this;
    }

    private boolean hasInspection_ ;
    /**
     * <code>bool hasInspection = 4;</code>
     * @return The hasInspection.
     */
    @java.lang.Override
    public boolean getHasInspection() {
      return hasInspection_;
    }
    /**
     * <code>bool hasInspection = 4;</code>
     * @param value The hasInspection to set.
     * @return This builder for chaining.
     */
    public Builder setHasInspection(boolean value) {
      
      hasInspection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasInspection = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasInspection() {
      
      hasInspection_ = false;
      onChanged();
      return this;
    }

    private double groundArea_ ;
    /**
     * <code>double groundArea = 5;</code>
     * @return The groundArea.
     */
    @java.lang.Override
    public double getGroundArea() {
      return groundArea_;
    }
    /**
     * <code>double groundArea = 5;</code>
     * @param value The groundArea to set.
     * @return This builder for chaining.
     */
    public Builder setGroundArea(double value) {
      
      groundArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double groundArea = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroundArea() {
      
      groundArea_ = 0D;
      onChanged();
      return this;
    }

    private double floorArea_ ;
    /**
     * <code>double floorArea = 6;</code>
     * @return The floorArea.
     */
    @java.lang.Override
    public double getFloorArea() {
      return floorArea_;
    }
    /**
     * <code>double floorArea = 6;</code>
     * @param value The floorArea to set.
     * @return This builder for chaining.
     */
    public Builder setFloorArea(double value) {
      
      floorArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double floorArea = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloorArea() {
      
      floorArea_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<com.group5.proto.Listing.ImageFileMessage> images_ =
      java.util.Collections.emptyList();
    private void ensureImagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        images_ = new java.util.ArrayList<com.group5.proto.Listing.ImageFileMessage>(images_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.group5.proto.Listing.ImageFileMessage, com.group5.proto.Listing.ImageFileMessage.Builder, com.group5.proto.Listing.ImageFileMessageOrBuilder> imagesBuilder_;

    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public java.util.List<com.group5.proto.Listing.ImageFileMessage> getImagesList() {
      if (imagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(images_);
      } else {
        return imagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public int getImagesCount() {
      if (imagesBuilder_ == null) {
        return images_.size();
      } else {
        return imagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public com.group5.proto.Listing.ImageFileMessage getImages(int index) {
      if (imagesBuilder_ == null) {
        return images_.get(index);
      } else {
        return imagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder setImages(
        int index, com.group5.proto.Listing.ImageFileMessage value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
      } else {
        imagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder setImages(
        int index, com.group5.proto.Listing.ImageFileMessage.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.set(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder addImages(com.group5.proto.Listing.ImageFileMessage value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      } else {
        imagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder addImages(
        int index, com.group5.proto.Listing.ImageFileMessage value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.add(index, value);
        onChanged();
      } else {
        imagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder addImages(
        com.group5.proto.Listing.ImageFileMessage.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.add(builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder addImages(
        int index, com.group5.proto.Listing.ImageFileMessage.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.add(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder addAllImages(
        java.lang.Iterable<? extends com.group5.proto.Listing.ImageFileMessage> values) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images_);
        onChanged();
      } else {
        imagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder clearImages() {
      if (imagesBuilder_ == null) {
        images_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public Builder removeImages(int index) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.remove(index);
        onChanged();
      } else {
        imagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public com.group5.proto.Listing.ImageFileMessage.Builder getImagesBuilder(
        int index) {
      return getImagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public com.group5.proto.Listing.ImageFileMessageOrBuilder getImagesOrBuilder(
        int index) {
      if (imagesBuilder_ == null) {
        return images_.get(index);  } else {
        return imagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public java.util.List<? extends com.group5.proto.Listing.ImageFileMessageOrBuilder> 
         getImagesOrBuilderList() {
      if (imagesBuilder_ != null) {
        return imagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(images_);
      }
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public com.group5.proto.Listing.ImageFileMessage.Builder addImagesBuilder() {
      return getImagesFieldBuilder().addBuilder(
          com.group5.proto.Listing.ImageFileMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public com.group5.proto.Listing.ImageFileMessage.Builder addImagesBuilder(
        int index) {
      return getImagesFieldBuilder().addBuilder(
          index, com.group5.proto.Listing.ImageFileMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
     */
    public java.util.List<com.group5.proto.Listing.ImageFileMessage.Builder> 
         getImagesBuilderList() {
      return getImagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.group5.proto.Listing.ImageFileMessage, com.group5.proto.Listing.ImageFileMessage.Builder, com.group5.proto.Listing.ImageFileMessageOrBuilder> 
        getImagesFieldBuilder() {
      if (imagesBuilder_ == null) {
        imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.group5.proto.Listing.ImageFileMessage, com.group5.proto.Listing.ImageFileMessage.Builder, com.group5.proto.Listing.ImageFileMessageOrBuilder>(
                images_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        images_ = null;
      }
      return imagesBuilder_;
    }

    private double price_ ;
    /**
     * <code>double price = 8;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 8;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object userEmail_ = "";
    /**
     * <code>string userEmail = 9;</code>
     * @return The userEmail.
     */
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userEmail = 9;</code>
     * @return The bytes for userEmail.
     */
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userEmail = 9;</code>
     * @param value The userEmail to set.
     * @return This builder for chaining.
     */
    public Builder setUserEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userEmail = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserEmail() {
      
      userEmail_ = getDefaultInstance().getUserEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string userEmail = 9;</code>
     * @param value The bytes for userEmail to set.
     * @return This builder for chaining.
     */
    public Builder setUserEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 10;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 10;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 10;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 10;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.group5.proto.Listing.CreateHouseListingRequest)
  }

  // @@protoc_insertion_point(class_scope:com.group5.proto.Listing.CreateHouseListingRequest)
  private static final com.group5.proto.Listing.CreateHouseListingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.group5.proto.Listing.CreateHouseListingRequest();
  }

  public static com.group5.proto.Listing.CreateHouseListingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateHouseListingRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateHouseListingRequest>() {
    @java.lang.Override
    public CreateHouseListingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateHouseListingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateHouseListingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateHouseListingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.group5.proto.Listing.CreateHouseListingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

