// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface CreateHouseListingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.CreateHouseListingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   * @return The address.
   */
  com.group5.proto.Listing.AddressMessage getAddress();
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 1;</code>
   */
  com.group5.proto.Listing.AddressMessageOrBuilder getAddressOrBuilder();

  /**
   * <code>int32 constructionYear = 2;</code>
   * @return The constructionYear.
   */
  int getConstructionYear();

  /**
   * <code>int32 lastRebuilt = 3;</code>
   * @return The lastRebuilt.
   */
  int getLastRebuilt();

  /**
   * <code>bool hasInspection = 4;</code>
   * @return The hasInspection.
   */
  boolean getHasInspection();

  /**
   * <code>double groundArea = 5;</code>
   * @return The groundArea.
   */
  double getGroundArea();

  /**
   * <code>double floorArea = 6;</code>
   * @return The floorArea.
   */
  double getFloorArea();

  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  java.util.List<com.group5.proto.Listing.ImageFileMessage> 
      getImagesList();
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  com.group5.proto.Listing.ImageFileMessage getImages(int index);
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  int getImagesCount();
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  java.util.List<? extends com.group5.proto.Listing.ImageFileMessageOrBuilder> 
      getImagesOrBuilderList();
  /**
   * <code>repeated .com.group5.proto.Listing.ImageFileMessage images = 7;</code>
   */
  com.group5.proto.Listing.ImageFileMessageOrBuilder getImagesOrBuilder(
      int index);

  /**
   * <code>double price = 8;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>string userEmail = 9;</code>
   * @return The userEmail.
   */
  java.lang.String getUserEmail();
  /**
   * <code>string userEmail = 9;</code>
   * @return The bytes for userEmail.
   */
  com.google.protobuf.ByteString
      getUserEmailBytes();

  /**
   * <code>string description = 10;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 10;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
