// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

/**
 * Protobuf type {@code com.group5.proto.Listing.CreateHouseListingRequest}
 */
public final class CreateHouseListingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.group5.proto.Listing.CreateHouseListingRequest)
    CreateHouseListingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateHouseListingRequest.newBuilder() to construct.
  private CreateHouseListingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateHouseListingRequest() {
    street_ = "";
    city_ = "";
    imageBase64Data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    imageContentType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    imageFileName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    userEmail_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateHouseListingRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateHouseListingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            street_ = s;
            break;
          }
          case 16: {

            postNumber_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 32: {

            houseNo_ = input.readInt32();
            break;
          }
          case 40: {

            constructionYear_ = input.readInt32();
            break;
          }
          case 48: {

            lastRebuilt_ = input.readInt32();
            break;
          }
          case 56: {

            hasInspection_ = input.readBool();
            break;
          }
          case 65: {

            groundArea_ = input.readDouble();
            break;
          }
          case 73: {

            floorArea_ = input.readDouble();
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              imageBase64Data_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            imageBase64Data_.add(s);
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              imageContentType_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            imageContentType_.add(s);
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              imageFileName_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            imageFileName_.add(s);
            break;
          }
          case 105: {

            price_ = input.readDouble();
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            userEmail_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        imageBase64Data_ = imageBase64Data_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        imageContentType_ = imageContentType_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        imageFileName_ = imageFileName_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CreateHouseListingRequest.class, Builder.class);
  }

  public static final int STREET_FIELD_NUMBER = 1;
  private volatile Object street_;
  /**
   * <code>string street = 1;</code>
   * @return The street.
   */
  @Override
  public String getStreet() {
    Object ref = street_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      street_ = s;
      return s;
    }
  }
  /**
   * <code>string street = 1;</code>
   * @return The bytes for street.
   */
  @Override
  public com.google.protobuf.ByteString
      getStreetBytes() {
    Object ref = street_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      street_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTNUMBER_FIELD_NUMBER = 2;
  private int postNumber_;
  /**
   * <code>int32 postNumber = 2;</code>
   * @return The postNumber.
   */
  @Override
  public int getPostNumber() {
    return postNumber_;
  }

  public static final int CITY_FIELD_NUMBER = 3;
  private volatile Object city_;
  /**
   * <code>string city = 3;</code>
   * @return The city.
   */
  @Override
  public String getCity() {
    Object ref = city_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 3;</code>
   * @return The bytes for city.
   */
  @Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    Object ref = city_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOUSENO_FIELD_NUMBER = 4;
  private int houseNo_;
  /**
   * <code>int32 houseNo = 4;</code>
   * @return The houseNo.
   */
  @Override
  public int getHouseNo() {
    return houseNo_;
  }

  public static final int CONSTRUCTIONYEAR_FIELD_NUMBER = 5;
  private int constructionYear_;
  /**
   * <code>int32 constructionYear = 5;</code>
   * @return The constructionYear.
   */
  @Override
  public int getConstructionYear() {
    return constructionYear_;
  }

  public static final int LASTREBUILT_FIELD_NUMBER = 6;
  private int lastRebuilt_;
  /**
   * <code>int32 lastRebuilt = 6;</code>
   * @return The lastRebuilt.
   */
  @Override
  public int getLastRebuilt() {
    return lastRebuilt_;
  }

  public static final int HASINSPECTION_FIELD_NUMBER = 7;
  private boolean hasInspection_;
  /**
   * <code>bool hasInspection = 7;</code>
   * @return The hasInspection.
   */
  @Override
  public boolean getHasInspection() {
    return hasInspection_;
  }

  public static final int GROUNDAREA_FIELD_NUMBER = 8;
  private double groundArea_;
  /**
   * <code>double groundArea = 8;</code>
   * @return The groundArea.
   */
  @Override
  public double getGroundArea() {
    return groundArea_;
  }

  public static final int FLOORAREA_FIELD_NUMBER = 9;
  private double floorArea_;
  /**
   * <code>double floorArea = 9;</code>
   * @return The floorArea.
   */
  @Override
  public double getFloorArea() {
    return floorArea_;
  }

  public static final int IMAGEBASE64DATA_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList imageBase64Data_;
  /**
   * <code>repeated string imageBase64Data = 10;</code>
   * @return A list containing the imageBase64Data.
   */
  public com.google.protobuf.ProtocolStringList
      getImageBase64DataList() {
    return imageBase64Data_;
  }
  /**
   * <code>repeated string imageBase64Data = 10;</code>
   * @return The count of imageBase64Data.
   */
  public int getImageBase64DataCount() {
    return imageBase64Data_.size();
  }
  /**
   * <code>repeated string imageBase64Data = 10;</code>
   * @param index The index of the element to return.
   * @return The imageBase64Data at the given index.
   */
  public String getImageBase64Data(int index) {
    return imageBase64Data_.get(index);
  }
  /**
   * <code>repeated string imageBase64Data = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imageBase64Data at the given index.
   */
  public com.google.protobuf.ByteString
      getImageBase64DataBytes(int index) {
    return imageBase64Data_.getByteString(index);
  }

  public static final int IMAGECONTENTTYPE_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList imageContentType_;
  /**
   * <code>repeated string imageContentType = 11;</code>
   * @return A list containing the imageContentType.
   */
  public com.google.protobuf.ProtocolStringList
      getImageContentTypeList() {
    return imageContentType_;
  }
  /**
   * <code>repeated string imageContentType = 11;</code>
   * @return The count of imageContentType.
   */
  public int getImageContentTypeCount() {
    return imageContentType_.size();
  }
  /**
   * <code>repeated string imageContentType = 11;</code>
   * @param index The index of the element to return.
   * @return The imageContentType at the given index.
   */
  public String getImageContentType(int index) {
    return imageContentType_.get(index);
  }
  /**
   * <code>repeated string imageContentType = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imageContentType at the given index.
   */
  public com.google.protobuf.ByteString
      getImageContentTypeBytes(int index) {
    return imageContentType_.getByteString(index);
  }

  public static final int IMAGEFILENAME_FIELD_NUMBER = 12;
  private com.google.protobuf.LazyStringList imageFileName_;
  /**
   * <code>repeated string imageFileName = 12;</code>
   * @return A list containing the imageFileName.
   */
  public com.google.protobuf.ProtocolStringList
      getImageFileNameList() {
    return imageFileName_;
  }
  /**
   * <code>repeated string imageFileName = 12;</code>
   * @return The count of imageFileName.
   */
  public int getImageFileNameCount() {
    return imageFileName_.size();
  }
  /**
   * <code>repeated string imageFileName = 12;</code>
   * @param index The index of the element to return.
   * @return The imageFileName at the given index.
   */
  public String getImageFileName(int index) {
    return imageFileName_.get(index);
  }
  /**
   * <code>repeated string imageFileName = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imageFileName at the given index.
   */
  public com.google.protobuf.ByteString
      getImageFileNameBytes(int index) {
    return imageFileName_.getByteString(index);
  }

  public static final int PRICE_FIELD_NUMBER = 13;
  private double price_;
  /**
   * <code>double price = 13;</code>
   * @return The price.
   */
  @Override
  public double getPrice() {
    return price_;
  }

  public static final int USEREMAIL_FIELD_NUMBER = 14;
  private volatile Object userEmail_;
  /**
   * <code>string userEmail = 14;</code>
   * @return The userEmail.
   */
  @Override
  public String getUserEmail() {
    Object ref = userEmail_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string userEmail = 14;</code>
   * @return The bytes for userEmail.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserEmailBytes() {
    Object ref = userEmail_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, street_);
    }
    if (postNumber_ != 0) {
      output.writeInt32(2, postNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
    }
    if (houseNo_ != 0) {
      output.writeInt32(4, houseNo_);
    }
    if (constructionYear_ != 0) {
      output.writeInt32(5, constructionYear_);
    }
    if (lastRebuilt_ != 0) {
      output.writeInt32(6, lastRebuilt_);
    }
    if (hasInspection_ != false) {
      output.writeBool(7, hasInspection_);
    }
    if (Double.doubleToRawLongBits(groundArea_) != 0) {
      output.writeDouble(8, groundArea_);
    }
    if (Double.doubleToRawLongBits(floorArea_) != 0) {
      output.writeDouble(9, floorArea_);
    }
    for (int i = 0; i < imageBase64Data_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, imageBase64Data_.getRaw(i));
    }
    for (int i = 0; i < imageContentType_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, imageContentType_.getRaw(i));
    }
    for (int i = 0; i < imageFileName_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, imageFileName_.getRaw(i));
    }
    if (Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(13, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, userEmail_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, street_);
    }
    if (postNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, postNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
    }
    if (houseNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, houseNo_);
    }
    if (constructionYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, constructionYear_);
    }
    if (lastRebuilt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, lastRebuilt_);
    }
    if (hasInspection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, hasInspection_);
    }
    if (Double.doubleToRawLongBits(groundArea_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, groundArea_);
    }
    if (Double.doubleToRawLongBits(floorArea_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, floorArea_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < imageBase64Data_.size(); i++) {
        dataSize += computeStringSizeNoTag(imageBase64Data_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImageBase64DataList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < imageContentType_.size(); i++) {
        dataSize += computeStringSizeNoTag(imageContentType_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImageContentTypeList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < imageFileName_.size(); i++) {
        dataSize += computeStringSizeNoTag(imageFileName_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImageFileNameList().size();
    }
    if (Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(13, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, userEmail_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CreateHouseListingRequest)) {
      return super.equals(obj);
    }
    CreateHouseListingRequest other = (CreateHouseListingRequest) obj;

    if (!getStreet()
        .equals(other.getStreet())) return false;
    if (getPostNumber()
        != other.getPostNumber()) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (getHouseNo()
        != other.getHouseNo()) return false;
    if (getConstructionYear()
        != other.getConstructionYear()) return false;
    if (getLastRebuilt()
        != other.getLastRebuilt()) return false;
    if (getHasInspection()
        != other.getHasInspection()) return false;
    if (Double.doubleToLongBits(getGroundArea())
        != Double.doubleToLongBits(
            other.getGroundArea())) return false;
    if (Double.doubleToLongBits(getFloorArea())
        != Double.doubleToLongBits(
            other.getFloorArea())) return false;
    if (!getImageBase64DataList()
        .equals(other.getImageBase64DataList())) return false;
    if (!getImageContentTypeList()
        .equals(other.getImageContentTypeList())) return false;
    if (!getImageFileNameList()
        .equals(other.getImageFileNameList())) return false;
    if (Double.doubleToLongBits(getPrice())
        != Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getUserEmail()
        .equals(other.getUserEmail())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STREET_FIELD_NUMBER;
    hash = (53 * hash) + getStreet().hashCode();
    hash = (37 * hash) + POSTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPostNumber();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + HOUSENO_FIELD_NUMBER;
    hash = (53 * hash) + getHouseNo();
    hash = (37 * hash) + CONSTRUCTIONYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getConstructionYear();
    hash = (37 * hash) + LASTREBUILT_FIELD_NUMBER;
    hash = (53 * hash) + getLastRebuilt();
    hash = (37 * hash) + HASINSPECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasInspection());
    hash = (37 * hash) + GROUNDAREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getGroundArea()));
    hash = (37 * hash) + FLOORAREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getFloorArea()));
    if (getImageBase64DataCount() > 0) {
      hash = (37 * hash) + IMAGEBASE64DATA_FIELD_NUMBER;
      hash = (53 * hash) + getImageBase64DataList().hashCode();
    }
    if (getImageContentTypeCount() > 0) {
      hash = (37 * hash) + IMAGECONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getImageContentTypeList().hashCode();
    }
    if (getImageFileNameCount() > 0) {
      hash = (37 * hash) + IMAGEFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getImageFileNameList().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getUserEmail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CreateHouseListingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreateHouseListingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreateHouseListingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreateHouseListingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreateHouseListingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreateHouseListingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreateHouseListingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreateHouseListingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreateHouseListingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CreateHouseListingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreateHouseListingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreateHouseListingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CreateHouseListingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.group5.proto.Listing.CreateHouseListingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.group5.proto.Listing.CreateHouseListingRequest)
      CreateHouseListingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreateHouseListingRequest.class, Builder.class);
    }

    // Construct using com.group5.proto.Listing.CreateHouseListingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      street_ = "";

      postNumber_ = 0;

      city_ = "";

      houseNo_ = 0;

      constructionYear_ = 0;

      lastRebuilt_ = 0;

      hasInspection_ = false;

      groundArea_ = 0D;

      floorArea_ = 0D;

      imageBase64Data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      imageContentType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      imageFileName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      price_ = 0D;

      userEmail_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Listing.internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
    }

    @Override
    public CreateHouseListingRequest getDefaultInstanceForType() {
      return CreateHouseListingRequest.getDefaultInstance();
    }

    @Override
    public CreateHouseListingRequest build() {
      CreateHouseListingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CreateHouseListingRequest buildPartial() {
      CreateHouseListingRequest result = new CreateHouseListingRequest(this);
      int from_bitField0_ = bitField0_;
      result.street_ = street_;
      result.postNumber_ = postNumber_;
      result.city_ = city_;
      result.houseNo_ = houseNo_;
      result.constructionYear_ = constructionYear_;
      result.lastRebuilt_ = lastRebuilt_;
      result.hasInspection_ = hasInspection_;
      result.groundArea_ = groundArea_;
      result.floorArea_ = floorArea_;
      if (((bitField0_ & 0x00000001) != 0)) {
        imageBase64Data_ = imageBase64Data_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.imageBase64Data_ = imageBase64Data_;
      if (((bitField0_ & 0x00000002) != 0)) {
        imageContentType_ = imageContentType_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.imageContentType_ = imageContentType_;
      if (((bitField0_ & 0x00000004) != 0)) {
        imageFileName_ = imageFileName_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.imageFileName_ = imageFileName_;
      result.price_ = price_;
      result.userEmail_ = userEmail_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CreateHouseListingRequest) {
        return mergeFrom((CreateHouseListingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CreateHouseListingRequest other) {
      if (other == CreateHouseListingRequest.getDefaultInstance()) return this;
      if (!other.getStreet().isEmpty()) {
        street_ = other.street_;
        onChanged();
      }
      if (other.getPostNumber() != 0) {
        setPostNumber(other.getPostNumber());
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (other.getHouseNo() != 0) {
        setHouseNo(other.getHouseNo());
      }
      if (other.getConstructionYear() != 0) {
        setConstructionYear(other.getConstructionYear());
      }
      if (other.getLastRebuilt() != 0) {
        setLastRebuilt(other.getLastRebuilt());
      }
      if (other.getHasInspection() != false) {
        setHasInspection(other.getHasInspection());
      }
      if (other.getGroundArea() != 0D) {
        setGroundArea(other.getGroundArea());
      }
      if (other.getFloorArea() != 0D) {
        setFloorArea(other.getFloorArea());
      }
      if (!other.imageBase64Data_.isEmpty()) {
        if (imageBase64Data_.isEmpty()) {
          imageBase64Data_ = other.imageBase64Data_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureImageBase64DataIsMutable();
          imageBase64Data_.addAll(other.imageBase64Data_);
        }
        onChanged();
      }
      if (!other.imageContentType_.isEmpty()) {
        if (imageContentType_.isEmpty()) {
          imageContentType_ = other.imageContentType_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureImageContentTypeIsMutable();
          imageContentType_.addAll(other.imageContentType_);
        }
        onChanged();
      }
      if (!other.imageFileName_.isEmpty()) {
        if (imageFileName_.isEmpty()) {
          imageFileName_ = other.imageFileName_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureImageFileNameIsMutable();
          imageFileName_.addAll(other.imageFileName_);
        }
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getUserEmail().isEmpty()) {
        userEmail_ = other.userEmail_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CreateHouseListingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CreateHouseListingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object street_ = "";
    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    public String getStreet() {
      Object ref = street_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        street_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string street = 1;</code>
     * @param value The street to set.
     * @return This builder for chaining.
     */
    public Builder setStreet(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      street_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string street = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreet() {
      
      street_ = getDefaultInstance().getStreet();
      onChanged();
      return this;
    }
    /**
     * <code>string street = 1;</code>
     * @param value The bytes for street to set.
     * @return This builder for chaining.
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      street_ = value;
      onChanged();
      return this;
    }

    private int postNumber_ ;
    /**
     * <code>int32 postNumber = 2;</code>
     * @return The postNumber.
     */
    @Override
    public int getPostNumber() {
      return postNumber_;
    }
    /**
     * <code>int32 postNumber = 2;</code>
     * @param value The postNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPostNumber(int value) {
      
      postNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 postNumber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostNumber() {
      
      postNumber_ = 0;
      onChanged();
      return this;
    }

    private Object city_ = "";
    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    public String getCity() {
      Object ref = city_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 3;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private int houseNo_ ;
    /**
     * <code>int32 houseNo = 4;</code>
     * @return The houseNo.
     */
    @Override
    public int getHouseNo() {
      return houseNo_;
    }
    /**
     * <code>int32 houseNo = 4;</code>
     * @param value The houseNo to set.
     * @return This builder for chaining.
     */
    public Builder setHouseNo(int value) {
      
      houseNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 houseNo = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHouseNo() {
      
      houseNo_ = 0;
      onChanged();
      return this;
    }

    private int constructionYear_ ;
    /**
     * <code>int32 constructionYear = 5;</code>
     * @return The constructionYear.
     */
    @Override
    public int getConstructionYear() {
      return constructionYear_;
    }
    /**
     * <code>int32 constructionYear = 5;</code>
     * @param value The constructionYear to set.
     * @return This builder for chaining.
     */
    public Builder setConstructionYear(int value) {
      
      constructionYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 constructionYear = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConstructionYear() {
      
      constructionYear_ = 0;
      onChanged();
      return this;
    }

    private int lastRebuilt_ ;
    /**
     * <code>int32 lastRebuilt = 6;</code>
     * @return The lastRebuilt.
     */
    @Override
    public int getLastRebuilt() {
      return lastRebuilt_;
    }
    /**
     * <code>int32 lastRebuilt = 6;</code>
     * @param value The lastRebuilt to set.
     * @return This builder for chaining.
     */
    public Builder setLastRebuilt(int value) {
      
      lastRebuilt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastRebuilt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastRebuilt() {
      
      lastRebuilt_ = 0;
      onChanged();
      return this;
    }

    private boolean hasInspection_ ;
    /**
     * <code>bool hasInspection = 7;</code>
     * @return The hasInspection.
     */
    @Override
    public boolean getHasInspection() {
      return hasInspection_;
    }
    /**
     * <code>bool hasInspection = 7;</code>
     * @param value The hasInspection to set.
     * @return This builder for chaining.
     */
    public Builder setHasInspection(boolean value) {
      
      hasInspection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasInspection = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasInspection() {
      
      hasInspection_ = false;
      onChanged();
      return this;
    }

    private double groundArea_ ;
    /**
     * <code>double groundArea = 8;</code>
     * @return The groundArea.
     */
    @Override
    public double getGroundArea() {
      return groundArea_;
    }
    /**
     * <code>double groundArea = 8;</code>
     * @param value The groundArea to set.
     * @return This builder for chaining.
     */
    public Builder setGroundArea(double value) {
      
      groundArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double groundArea = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroundArea() {
      
      groundArea_ = 0D;
      onChanged();
      return this;
    }

    private double floorArea_ ;
    /**
     * <code>double floorArea = 9;</code>
     * @return The floorArea.
     */
    @Override
    public double getFloorArea() {
      return floorArea_;
    }
    /**
     * <code>double floorArea = 9;</code>
     * @param value The floorArea to set.
     * @return This builder for chaining.
     */
    public Builder setFloorArea(double value) {
      
      floorArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double floorArea = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloorArea() {
      
      floorArea_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList imageBase64Data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImageBase64DataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        imageBase64Data_ = new com.google.protobuf.LazyStringArrayList(imageBase64Data_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @return A list containing the imageBase64Data.
     */
    public com.google.protobuf.ProtocolStringList
        getImageBase64DataList() {
      return imageBase64Data_.getUnmodifiableView();
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @return The count of imageBase64Data.
     */
    public int getImageBase64DataCount() {
      return imageBase64Data_.size();
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param index The index of the element to return.
     * @return The imageBase64Data at the given index.
     */
    public String getImageBase64Data(int index) {
      return imageBase64Data_.get(index);
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the imageBase64Data at the given index.
     */
    public com.google.protobuf.ByteString
        getImageBase64DataBytes(int index) {
      return imageBase64Data_.getByteString(index);
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param index The index to set the value at.
     * @param value The imageBase64Data to set.
     * @return This builder for chaining.
     */
    public Builder setImageBase64Data(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageBase64DataIsMutable();
      imageBase64Data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param value The imageBase64Data to add.
     * @return This builder for chaining.
     */
    public Builder addImageBase64Data(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageBase64DataIsMutable();
      imageBase64Data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param values The imageBase64Data to add.
     * @return This builder for chaining.
     */
    public Builder addAllImageBase64Data(
        Iterable<String> values) {
      ensureImageBase64DataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, imageBase64Data_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageBase64Data() {
      imageBase64Data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageBase64Data = 10;</code>
     * @param value The bytes of the imageBase64Data to add.
     * @return This builder for chaining.
     */
    public Builder addImageBase64DataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureImageBase64DataIsMutable();
      imageBase64Data_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList imageContentType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImageContentTypeIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        imageContentType_ = new com.google.protobuf.LazyStringArrayList(imageContentType_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @return A list containing the imageContentType.
     */
    public com.google.protobuf.ProtocolStringList
        getImageContentTypeList() {
      return imageContentType_.getUnmodifiableView();
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @return The count of imageContentType.
     */
    public int getImageContentTypeCount() {
      return imageContentType_.size();
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param index The index of the element to return.
     * @return The imageContentType at the given index.
     */
    public String getImageContentType(int index) {
      return imageContentType_.get(index);
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the imageContentType at the given index.
     */
    public com.google.protobuf.ByteString
        getImageContentTypeBytes(int index) {
      return imageContentType_.getByteString(index);
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param index The index to set the value at.
     * @param value The imageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setImageContentType(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageContentTypeIsMutable();
      imageContentType_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param value The imageContentType to add.
     * @return This builder for chaining.
     */
    public Builder addImageContentType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageContentTypeIsMutable();
      imageContentType_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param values The imageContentType to add.
     * @return This builder for chaining.
     */
    public Builder addAllImageContentType(
        Iterable<String> values) {
      ensureImageContentTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, imageContentType_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageContentType() {
      imageContentType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageContentType = 11;</code>
     * @param value The bytes of the imageContentType to add.
     * @return This builder for chaining.
     */
    public Builder addImageContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureImageContentTypeIsMutable();
      imageContentType_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList imageFileName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImageFileNameIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        imageFileName_ = new com.google.protobuf.LazyStringArrayList(imageFileName_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @return A list containing the imageFileName.
     */
    public com.google.protobuf.ProtocolStringList
        getImageFileNameList() {
      return imageFileName_.getUnmodifiableView();
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @return The count of imageFileName.
     */
    public int getImageFileNameCount() {
      return imageFileName_.size();
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param index The index of the element to return.
     * @return The imageFileName at the given index.
     */
    public String getImageFileName(int index) {
      return imageFileName_.get(index);
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param index The index of the value to return.
     * @return The bytes of the imageFileName at the given index.
     */
    public com.google.protobuf.ByteString
        getImageFileNameBytes(int index) {
      return imageFileName_.getByteString(index);
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param index The index to set the value at.
     * @param value The imageFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImageFileName(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageFileNameIsMutable();
      imageFileName_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param value The imageFileName to add.
     * @return This builder for chaining.
     */
    public Builder addImageFileName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImageFileNameIsMutable();
      imageFileName_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param values The imageFileName to add.
     * @return This builder for chaining.
     */
    public Builder addAllImageFileName(
        Iterable<String> values) {
      ensureImageFileNameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, imageFileName_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageFileName() {
      imageFileName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imageFileName = 12;</code>
     * @param value The bytes of the imageFileName to add.
     * @return This builder for chaining.
     */
    public Builder addImageFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureImageFileNameIsMutable();
      imageFileName_.add(value);
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 13;</code>
     * @return The price.
     */
    @Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 13;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private Object userEmail_ = "";
    /**
     * <code>string userEmail = 14;</code>
     * @return The userEmail.
     */
    public String getUserEmail() {
      Object ref = userEmail_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string userEmail = 14;</code>
     * @return The bytes for userEmail.
     */
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      Object ref = userEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userEmail = 14;</code>
     * @param value The userEmail to set.
     * @return This builder for chaining.
     */
    public Builder setUserEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userEmail = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserEmail() {
      
      userEmail_ = getDefaultInstance().getUserEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string userEmail = 14;</code>
     * @param value The bytes for userEmail to set.
     * @return This builder for chaining.
     */
    public Builder setUserEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userEmail_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.group5.proto.Listing.CreateHouseListingRequest)
  }

  // @@protoc_insertion_point(class_scope:com.group5.proto.Listing.CreateHouseListingRequest)
  private static final CreateHouseListingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreateHouseListingRequest();
  }

  public static CreateHouseListingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateHouseListingRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateHouseListingRequest>() {
    @Override
    public CreateHouseListingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateHouseListingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateHouseListingRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CreateHouseListingRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CreateHouseListingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

