// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 Id = 1;</code>
   * @return The id.
   */
  long getId();
}
