// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

/**
 * Protobuf type {@code com.group5.proto.Listing.ImageFileMessage}
 */
public final class ImageFileMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.group5.proto.Listing.ImageFileMessage)
    ImageFileMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImageFileMessage.newBuilder() to construct.
  private ImageFileMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImageFileMessage() {
    imageBase64Data_ = "";
    imageContentType_ = "";
    imageFileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImageFileMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImageFileMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            imageBase64Data_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            imageContentType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            imageFileName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_ImageFileMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_ImageFileMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.group5.proto.Listing.ImageFileMessage.class, com.group5.proto.Listing.ImageFileMessage.Builder.class);
  }

  public static final int IMAGEBASE64DATA_FIELD_NUMBER = 1;
  private volatile java.lang.Object imageBase64Data_;
  /**
   * <code>string imageBase64Data = 1;</code>
   * @return The imageBase64Data.
   */
  @java.lang.Override
  public java.lang.String getImageBase64Data() {
    java.lang.Object ref = imageBase64Data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageBase64Data_ = s;
      return s;
    }
  }
  /**
   * <code>string imageBase64Data = 1;</code>
   * @return The bytes for imageBase64Data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageBase64DataBytes() {
    java.lang.Object ref = imageBase64Data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageBase64Data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGECONTENTTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object imageContentType_;
  /**
   * <code>string imageContentType = 2;</code>
   * @return The imageContentType.
   */
  @java.lang.Override
  public java.lang.String getImageContentType() {
    java.lang.Object ref = imageContentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageContentType_ = s;
      return s;
    }
  }
  /**
   * <code>string imageContentType = 2;</code>
   * @return The bytes for imageContentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageContentTypeBytes() {
    java.lang.Object ref = imageContentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageContentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEFILENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object imageFileName_;
  /**
   * <code>string imageFileName = 3;</code>
   * @return The imageFileName.
   */
  @java.lang.Override
  public java.lang.String getImageFileName() {
    java.lang.Object ref = imageFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string imageFileName = 3;</code>
   * @return The bytes for imageFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageFileNameBytes() {
    java.lang.Object ref = imageFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageBase64Data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, imageBase64Data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageContentType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageFileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageFileName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageBase64Data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, imageBase64Data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageContentType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageFileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageFileName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.group5.proto.Listing.ImageFileMessage)) {
      return super.equals(obj);
    }
    com.group5.proto.Listing.ImageFileMessage other = (com.group5.proto.Listing.ImageFileMessage) obj;

    if (!getImageBase64Data()
        .equals(other.getImageBase64Data())) return false;
    if (!getImageContentType()
        .equals(other.getImageContentType())) return false;
    if (!getImageFileName()
        .equals(other.getImageFileName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IMAGEBASE64DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageBase64Data().hashCode();
    hash = (37 * hash) + IMAGECONTENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getImageContentType().hashCode();
    hash = (37 * hash) + IMAGEFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getImageFileName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.group5.proto.Listing.ImageFileMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.group5.proto.Listing.ImageFileMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.group5.proto.Listing.ImageFileMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.group5.proto.Listing.ImageFileMessage)
      com.group5.proto.Listing.ImageFileMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_ImageFileMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_ImageFileMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.group5.proto.Listing.ImageFileMessage.class, com.group5.proto.Listing.ImageFileMessage.Builder.class);
    }

    // Construct using com.group5.proto.Listing.ImageFileMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      imageBase64Data_ = "";

      imageContentType_ = "";

      imageFileName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.group5.proto.Listing.Listing.internal_static_com_group5_proto_Listing_ImageFileMessage_descriptor;
    }

    @java.lang.Override
    public com.group5.proto.Listing.ImageFileMessage getDefaultInstanceForType() {
      return com.group5.proto.Listing.ImageFileMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.group5.proto.Listing.ImageFileMessage build() {
      com.group5.proto.Listing.ImageFileMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.group5.proto.Listing.ImageFileMessage buildPartial() {
      com.group5.proto.Listing.ImageFileMessage result = new com.group5.proto.Listing.ImageFileMessage(this);
      result.imageBase64Data_ = imageBase64Data_;
      result.imageContentType_ = imageContentType_;
      result.imageFileName_ = imageFileName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.group5.proto.Listing.ImageFileMessage) {
        return mergeFrom((com.group5.proto.Listing.ImageFileMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.group5.proto.Listing.ImageFileMessage other) {
      if (other == com.group5.proto.Listing.ImageFileMessage.getDefaultInstance()) return this;
      if (!other.getImageBase64Data().isEmpty()) {
        imageBase64Data_ = other.imageBase64Data_;
        onChanged();
      }
      if (!other.getImageContentType().isEmpty()) {
        imageContentType_ = other.imageContentType_;
        onChanged();
      }
      if (!other.getImageFileName().isEmpty()) {
        imageFileName_ = other.imageFileName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.group5.proto.Listing.ImageFileMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.group5.proto.Listing.ImageFileMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object imageBase64Data_ = "";
    /**
     * <code>string imageBase64Data = 1;</code>
     * @return The imageBase64Data.
     */
    public java.lang.String getImageBase64Data() {
      java.lang.Object ref = imageBase64Data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageBase64Data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageBase64Data = 1;</code>
     * @return The bytes for imageBase64Data.
     */
    public com.google.protobuf.ByteString
        getImageBase64DataBytes() {
      java.lang.Object ref = imageBase64Data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageBase64Data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageBase64Data = 1;</code>
     * @param value The imageBase64Data to set.
     * @return This builder for chaining.
     */
    public Builder setImageBase64Data(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageBase64Data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageBase64Data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageBase64Data() {
      
      imageBase64Data_ = getDefaultInstance().getImageBase64Data();
      onChanged();
      return this;
    }
    /**
     * <code>string imageBase64Data = 1;</code>
     * @param value The bytes for imageBase64Data to set.
     * @return This builder for chaining.
     */
    public Builder setImageBase64DataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageBase64Data_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imageContentType_ = "";
    /**
     * <code>string imageContentType = 2;</code>
     * @return The imageContentType.
     */
    public java.lang.String getImageContentType() {
      java.lang.Object ref = imageContentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageContentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageContentType = 2;</code>
     * @return The bytes for imageContentType.
     */
    public com.google.protobuf.ByteString
        getImageContentTypeBytes() {
      java.lang.Object ref = imageContentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageContentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageContentType = 2;</code>
     * @param value The imageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setImageContentType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageContentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageContentType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageContentType() {
      
      imageContentType_ = getDefaultInstance().getImageContentType();
      onChanged();
      return this;
    }
    /**
     * <code>string imageContentType = 2;</code>
     * @param value The bytes for imageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setImageContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageContentType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imageFileName_ = "";
    /**
     * <code>string imageFileName = 3;</code>
     * @return The imageFileName.
     */
    public java.lang.String getImageFileName() {
      java.lang.Object ref = imageFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imageFileName = 3;</code>
     * @return The bytes for imageFileName.
     */
    public com.google.protobuf.ByteString
        getImageFileNameBytes() {
      java.lang.Object ref = imageFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageFileName = 3;</code>
     * @param value The imageFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImageFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageFileName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageFileName() {
      
      imageFileName_ = getDefaultInstance().getImageFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string imageFileName = 3;</code>
     * @param value The bytes for imageFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImageFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageFileName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.group5.proto.Listing.ImageFileMessage)
  }

  // @@protoc_insertion_point(class_scope:com.group5.proto.Listing.ImageFileMessage)
  private static final com.group5.proto.Listing.ImageFileMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.group5.proto.Listing.ImageFileMessage();
  }

  public static com.group5.proto.Listing.ImageFileMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImageFileMessage>
      PARSER = new com.google.protobuf.AbstractParser<ImageFileMessage>() {
    @java.lang.Override
    public ImageFileMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImageFileMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImageFileMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImageFileMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.group5.proto.Listing.ImageFileMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

