// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface IsOkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.IsOk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isOk = 1;</code>
   * @return The isOk.
   */
  boolean getIsOk();
}
