// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface ListingFiltersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.ListingFiltersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string city = 1;</code>
   * @return Whether the city field is set.
   */
  boolean hasCity();
  /**
   * <code>optional string city = 1;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>optional int64 maxPrice = 2;</code>
   * @return Whether the maxPrice field is set.
   */
  boolean hasMaxPrice();
  /**
   * <code>optional int64 maxPrice = 2;</code>
   * @return The maxPrice.
   */
  long getMaxPrice();

  /**
   * <code>optional int64 minArea = 3;</code>
   * @return Whether the minArea field is set.
   */
  boolean hasMinArea();
  /**
   * <code>optional int64 minArea = 3;</code>
   * @return The minArea.
   */
  long getMinArea();
}
