// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public final class Listing {
  private Listing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_IdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_IdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_HouseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_HouseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_ListingFiltersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_ListingFiltersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rListing.proto\022\030com.group5.proto.Listin" +
      "g\"\244\002\n\031CreateHouseListingRequest\022\016\n\006stree" +
      "t\030\001 \001(\t\022\022\n\npostNumber\030\002 \001(\005\022\014\n\004city\030\003 \001(" +
      "\t\022\017\n\007houseNo\030\004 \001(\005\022\030\n\020constructionYear\030\005" +
      " \001(\005\022\023\n\013lastRebuilt\030\006 \001(\005\022\025\n\rhasInspecti" +
      "on\030\007 \001(\010\022\022\n\ngroundArea\030\010 \001(\001\022\021\n\tfloorAre" +
      "a\030\t \001(\001\022\027\n\017imageBase64Data\030\n \003(\t\022\030\n\020imag" +
      "eContentType\030\013 \003(\t\022\025\n\rimageFileName\030\014 \003(" +
      "\t\022\r\n\005price\030\r \001(\001\"\027\n\tIdRequest\022\n\n\002Id\030\001 \001(" +
      "\003\"\272\002\n\rHouseResponse\022\n\n\002id\030\001 \001(\003\022\016\n\006stree" +
      "t\030\002 \001(\t\022\022\n\npostNumber\030\003 \001(\005\022\014\n\004city\030\004 \001(" +
      "\t\022\017\n\007houseNo\030\005 \001(\005\022\030\n\020constructionYear\030\006" +
      " \001(\005\022\023\n\013lastRebuilt\030\007 \001(\005\022\025\n\rhasInspecti" +
      "on\030\010 \001(\010\022\022\n\ngroundArea\030\t \001(\001\022\021\n\tfloorAre" +
      "a\030\n \001(\001\022\027\n\017imageBase64Data\030\013 \003(\t\022\030\n\020imag" +
      "eContentType\030\014 \003(\t\022\025\n\rimageFileName\030\r \003(" +
      "\t\022\r\n\005price\030\016 \001(\001\022\024\n\014creationDate\030\017 \001(\t\"\205" +
      "\001\n\025ListingFiltersRequest\022\027\n\npostNumber\030\001" +
      " \001(\003H\000\210\001\001\022\025\n\010maxPrice\030\002 \001(\003H\001\210\001\001\022\024\n\007minA" +
      "rea\030\003 \001(\003H\002\210\001\001B\r\n\013_postNumberB\013\n\t_maxPri" +
      "ceB\n\n\010_minArea\"\262\001\n\024ShortListingResponse\022" +
      "\r\n\005price\030\001 \001(\003\022\027\n\017imageBase64Data\030\002 \001(\t\022" +
      "\030\n\020imageContentType\030\003 \001(\t\022\025\n\rimageFileNa" +
      "me\030\004 \001(\t\022\016\n\006street\030\005 \001(\t\022\022\n\npostNumber\030\006" +
      " \001(\005\022\014\n\004city\030\007 \001(\t\022\017\n\007houseNo\030\010 \001(\0052\331\002\n\016" +
      "ListingService\022m\n\rcreateListing\0223.com.gr" +
      "oup5.proto.Listing.CreateHouseListingReq" +
      "uest\032\'.com.group5.proto.Listing.HouseRes" +
      "ponse\022^\n\016getListingById\022#.com.group5.pro" +
      "to.Listing.IdRequest\032\'.com.group5.proto." +
      "Listing.HouseResponse\022x\n\023getFilteredList" +
      "ings\022/.com.group5.proto.Listing.ListingF" +
      "iltersRequest\032..com.group5.proto.Listing" +
      ".ShortListingResponse0\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor,
        new java.lang.String[] { "Street", "PostNumber", "City", "HouseNo", "ConstructionYear", "LastRebuilt", "HasInspection", "GroundArea", "FloorArea", "ImageBase64Data", "ImageContentType", "ImageFileName", "Price", });
    internal_static_com_group5_proto_Listing_IdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_group5_proto_Listing_IdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_IdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_group5_proto_Listing_HouseResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_group5_proto_Listing_HouseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_HouseResponse_descriptor,
        new java.lang.String[] { "Id", "Street", "PostNumber", "City", "HouseNo", "ConstructionYear", "LastRebuilt", "HasInspection", "GroundArea", "FloorArea", "ImageBase64Data", "ImageContentType", "ImageFileName", "Price", "CreationDate", });
    internal_static_com_group5_proto_Listing_ListingFiltersRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_group5_proto_Listing_ListingFiltersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_ListingFiltersRequest_descriptor,
        new java.lang.String[] { "PostNumber", "MaxPrice", "MinArea", "PostNumber", "MaxPrice", "MinArea", });
    internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor,
        new java.lang.String[] { "Price", "ImageBase64Data", "ImageContentType", "ImageFileName", "Street", "PostNumber", "City", "HouseNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
