// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface ShortListingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.ShortListingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 price = 1;</code>
   * @return The price.
   */
  long getPrice();

  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The imageBase64Data.
   */
  String getImageBase64Data();
  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The bytes for imageBase64Data.
   */
  com.google.protobuf.ByteString
      getImageBase64DataBytes();

  /**
   * <code>string imageContentType = 3;</code>
   * @return The imageContentType.
   */
  String getImageContentType();
  /**
   * <code>string imageContentType = 3;</code>
   * @return The bytes for imageContentType.
   */
  com.google.protobuf.ByteString
      getImageContentTypeBytes();

  /**
   * <code>string imageFileName = 4;</code>
   * @return The imageFileName.
   */
  String getImageFileName();
  /**
   * <code>string imageFileName = 4;</code>
   * @return The bytes for imageFileName.
   */
  com.google.protobuf.ByteString
      getImageFileNameBytes();

  /**
   * <code>string street = 5;</code>
   * @return The street.
   */
  String getStreet();
  /**
   * <code>string street = 5;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>int32 postNumber = 6;</code>
   * @return The postNumber.
   */
  int getPostNumber();

  /**
   * <code>string city = 7;</code>
   * @return The city.
   */
  String getCity();
  /**
   * <code>string city = 7;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>int32 houseNo = 8;</code>
   * @return The houseNo.
   */
  int getHouseNo();

  /**
   * <code>int64 id = 9;</code>
   * @return The id.
   */
  long getId();
}
