// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

/**
 * Protobuf type {@code com.group5.proto.Listing.ShortListingResponse}
 */
public final class ShortListingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.group5.proto.Listing.ShortListingResponse)
    ShortListingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShortListingResponse.newBuilder() to construct.
  private ShortListingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShortListingResponse() {
    imageBase64Data_ = "";
    imageContentType_ = "";
    imageFileName_ = "";
    street_ = "";
    city_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShortListingResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShortListingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            price_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            imageBase64Data_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            imageContentType_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            imageFileName_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            street_ = s;
            break;
          }
          case 48: {

            postNumber_ = input.readInt32();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 64: {

            houseNo_ = input.readInt32();
            break;
          }
          case 72: {

            id_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ShortListingResponse.class, Builder.class);
  }

  public static final int PRICE_FIELD_NUMBER = 1;
  private long price_;
  /**
   * <code>int64 price = 1;</code>
   * @return The price.
   */
  @Override
  public long getPrice() {
    return price_;
  }

  public static final int IMAGEBASE64DATA_FIELD_NUMBER = 2;
  private volatile Object imageBase64Data_;
  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The imageBase64Data.
   */
  @Override
  public String getImageBase64Data() {
    Object ref = imageBase64Data_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      imageBase64Data_ = s;
      return s;
    }
  }
  /**
   * <code>string imageBase64Data = 2;</code>
   * @return The bytes for imageBase64Data.
   */
  @Override
  public com.google.protobuf.ByteString
      getImageBase64DataBytes() {
    Object ref = imageBase64Data_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      imageBase64Data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGECONTENTTYPE_FIELD_NUMBER = 3;
  private volatile Object imageContentType_;
  /**
   * <code>string imageContentType = 3;</code>
   * @return The imageContentType.
   */
  @Override
  public String getImageContentType() {
    Object ref = imageContentType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      imageContentType_ = s;
      return s;
    }
  }
  /**
   * <code>string imageContentType = 3;</code>
   * @return The bytes for imageContentType.
   */
  @Override
  public com.google.protobuf.ByteString
      getImageContentTypeBytes() {
    Object ref = imageContentType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      imageContentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEFILENAME_FIELD_NUMBER = 4;
  private volatile Object imageFileName_;
  /**
   * <code>string imageFileName = 4;</code>
   * @return The imageFileName.
   */
  @Override
  public String getImageFileName() {
    Object ref = imageFileName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      imageFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string imageFileName = 4;</code>
   * @return The bytes for imageFileName.
   */
  @Override
  public com.google.protobuf.ByteString
      getImageFileNameBytes() {
    Object ref = imageFileName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      imageFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_FIELD_NUMBER = 5;
  private volatile Object street_;
  /**
   * <code>string street = 5;</code>
   * @return The street.
   */
  @Override
  public String getStreet() {
    Object ref = street_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      street_ = s;
      return s;
    }
  }
  /**
   * <code>string street = 5;</code>
   * @return The bytes for street.
   */
  @Override
  public com.google.protobuf.ByteString
      getStreetBytes() {
    Object ref = street_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      street_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTNUMBER_FIELD_NUMBER = 6;
  private int postNumber_;
  /**
   * <code>int32 postNumber = 6;</code>
   * @return The postNumber.
   */
  @Override
  public int getPostNumber() {
    return postNumber_;
  }

  public static final int CITY_FIELD_NUMBER = 7;
  private volatile Object city_;
  /**
   * <code>string city = 7;</code>
   * @return The city.
   */
  @Override
  public String getCity() {
    Object ref = city_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 7;</code>
   * @return The bytes for city.
   */
  @Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    Object ref = city_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOUSENO_FIELD_NUMBER = 8;
  private int houseNo_;
  /**
   * <code>int32 houseNo = 8;</code>
   * @return The houseNo.
   */
  @Override
  public int getHouseNo() {
    return houseNo_;
  }

  public static final int ID_FIELD_NUMBER = 9;
  private long id_;
  /**
   * <code>int64 id = 9;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (price_ != 0L) {
      output.writeInt64(1, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageBase64Data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageBase64Data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageContentType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageFileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageFileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, street_);
    }
    if (postNumber_ != 0) {
      output.writeInt32(6, postNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, city_);
    }
    if (houseNo_ != 0) {
      output.writeInt32(8, houseNo_);
    }
    if (id_ != 0L) {
      output.writeInt64(9, id_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (price_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageBase64Data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageBase64Data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageContentType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageFileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageFileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, street_);
    }
    if (postNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, postNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, city_);
    }
    if (houseNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, houseNo_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ShortListingResponse)) {
      return super.equals(obj);
    }
    ShortListingResponse other = (ShortListingResponse) obj;

    if (getPrice()
        != other.getPrice()) return false;
    if (!getImageBase64Data()
        .equals(other.getImageBase64Data())) return false;
    if (!getImageContentType()
        .equals(other.getImageContentType())) return false;
    if (!getImageFileName()
        .equals(other.getImageFileName())) return false;
    if (!getStreet()
        .equals(other.getStreet())) return false;
    if (getPostNumber()
        != other.getPostNumber()) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (getHouseNo()
        != other.getHouseNo()) return false;
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrice());
    hash = (37 * hash) + IMAGEBASE64DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageBase64Data().hashCode();
    hash = (37 * hash) + IMAGECONTENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getImageContentType().hashCode();
    hash = (37 * hash) + IMAGEFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getImageFileName().hashCode();
    hash = (37 * hash) + STREET_FIELD_NUMBER;
    hash = (53 * hash) + getStreet().hashCode();
    hash = (37 * hash) + POSTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPostNumber();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + HOUSENO_FIELD_NUMBER;
    hash = (53 * hash) + getHouseNo();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ShortListingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShortListingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ShortListingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.group5.proto.Listing.ShortListingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.group5.proto.Listing.ShortListingResponse)
      ShortListingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShortListingResponse.class, Builder.class);
    }

    // Construct using com.group5.proto.Listing.ShortListingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      price_ = 0L;

      imageBase64Data_ = "";

      imageContentType_ = "";

      imageFileName_ = "";

      street_ = "";

      postNumber_ = 0;

      city_ = "";

      houseNo_ = 0;

      id_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
    }

    @Override
    public ShortListingResponse getDefaultInstanceForType() {
      return ShortListingResponse.getDefaultInstance();
    }

    @Override
    public ShortListingResponse build() {
      ShortListingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ShortListingResponse buildPartial() {
      ShortListingResponse result = new ShortListingResponse(this);
      result.price_ = price_;
      result.imageBase64Data_ = imageBase64Data_;
      result.imageContentType_ = imageContentType_;
      result.imageFileName_ = imageFileName_;
      result.street_ = street_;
      result.postNumber_ = postNumber_;
      result.city_ = city_;
      result.houseNo_ = houseNo_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ShortListingResponse) {
        return mergeFrom((ShortListingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ShortListingResponse other) {
      if (other == ShortListingResponse.getDefaultInstance()) return this;
      if (other.getPrice() != 0L) {
        setPrice(other.getPrice());
      }
      if (!other.getImageBase64Data().isEmpty()) {
        imageBase64Data_ = other.imageBase64Data_;
        onChanged();
      }
      if (!other.getImageContentType().isEmpty()) {
        imageContentType_ = other.imageContentType_;
        onChanged();
      }
      if (!other.getImageFileName().isEmpty()) {
        imageFileName_ = other.imageFileName_;
        onChanged();
      }
      if (!other.getStreet().isEmpty()) {
        street_ = other.street_;
        onChanged();
      }
      if (other.getPostNumber() != 0) {
        setPostNumber(other.getPostNumber());
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (other.getHouseNo() != 0) {
        setHouseNo(other.getHouseNo());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ShortListingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ShortListingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long price_ ;
    /**
     * <code>int64 price = 1;</code>
     * @return The price.
     */
    @Override
    public long getPrice() {
      return price_;
    }
    /**
     * <code>int64 price = 1;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(long value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 price = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0L;
      onChanged();
      return this;
    }

    private Object imageBase64Data_ = "";
    /**
     * <code>string imageBase64Data = 2;</code>
     * @return The imageBase64Data.
     */
    public String getImageBase64Data() {
      Object ref = imageBase64Data_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageBase64Data_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string imageBase64Data = 2;</code>
     * @return The bytes for imageBase64Data.
     */
    public com.google.protobuf.ByteString
        getImageBase64DataBytes() {
      Object ref = imageBase64Data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageBase64Data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageBase64Data = 2;</code>
     * @param value The imageBase64Data to set.
     * @return This builder for chaining.
     */
    public Builder setImageBase64Data(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageBase64Data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageBase64Data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageBase64Data() {
      
      imageBase64Data_ = getDefaultInstance().getImageBase64Data();
      onChanged();
      return this;
    }
    /**
     * <code>string imageBase64Data = 2;</code>
     * @param value The bytes for imageBase64Data to set.
     * @return This builder for chaining.
     */
    public Builder setImageBase64DataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageBase64Data_ = value;
      onChanged();
      return this;
    }

    private Object imageContentType_ = "";
    /**
     * <code>string imageContentType = 3;</code>
     * @return The imageContentType.
     */
    public String getImageContentType() {
      Object ref = imageContentType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageContentType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string imageContentType = 3;</code>
     * @return The bytes for imageContentType.
     */
    public com.google.protobuf.ByteString
        getImageContentTypeBytes() {
      Object ref = imageContentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageContentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageContentType = 3;</code>
     * @param value The imageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setImageContentType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageContentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageContentType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageContentType() {
      
      imageContentType_ = getDefaultInstance().getImageContentType();
      onChanged();
      return this;
    }
    /**
     * <code>string imageContentType = 3;</code>
     * @param value The bytes for imageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setImageContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageContentType_ = value;
      onChanged();
      return this;
    }

    private Object imageFileName_ = "";
    /**
     * <code>string imageFileName = 4;</code>
     * @return The imageFileName.
     */
    public String getImageFileName() {
      Object ref = imageFileName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageFileName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string imageFileName = 4;</code>
     * @return The bytes for imageFileName.
     */
    public com.google.protobuf.ByteString
        getImageFileNameBytes() {
      Object ref = imageFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imageFileName = 4;</code>
     * @param value The imageFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImageFileName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imageFileName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageFileName() {
      
      imageFileName_ = getDefaultInstance().getImageFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string imageFileName = 4;</code>
     * @param value The bytes for imageFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImageFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageFileName_ = value;
      onChanged();
      return this;
    }

    private Object street_ = "";
    /**
     * <code>string street = 5;</code>
     * @return The street.
     */
    public String getStreet() {
      Object ref = street_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        street_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string street = 5;</code>
     * @return The bytes for street.
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string street = 5;</code>
     * @param value The street to set.
     * @return This builder for chaining.
     */
    public Builder setStreet(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      street_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string street = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreet() {
      
      street_ = getDefaultInstance().getStreet();
      onChanged();
      return this;
    }
    /**
     * <code>string street = 5;</code>
     * @param value The bytes for street to set.
     * @return This builder for chaining.
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      street_ = value;
      onChanged();
      return this;
    }

    private int postNumber_ ;
    /**
     * <code>int32 postNumber = 6;</code>
     * @return The postNumber.
     */
    @Override
    public int getPostNumber() {
      return postNumber_;
    }
    /**
     * <code>int32 postNumber = 6;</code>
     * @param value The postNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPostNumber(int value) {
      
      postNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 postNumber = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostNumber() {
      
      postNumber_ = 0;
      onChanged();
      return this;
    }

    private Object city_ = "";
    /**
     * <code>string city = 7;</code>
     * @return The city.
     */
    public String getCity() {
      Object ref = city_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string city = 7;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 7;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 7;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private int houseNo_ ;
    /**
     * <code>int32 houseNo = 8;</code>
     * @return The houseNo.
     */
    @Override
    public int getHouseNo() {
      return houseNo_;
    }
    /**
     * <code>int32 houseNo = 8;</code>
     * @param value The houseNo to set.
     * @return This builder for chaining.
     */
    public Builder setHouseNo(int value) {
      
      houseNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 houseNo = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHouseNo() {
      
      houseNo_ = 0;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 9;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 9;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.group5.proto.Listing.ShortListingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.group5.proto.Listing.ShortListingResponse)
  private static final ShortListingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ShortListingResponse();
  }

  public static ShortListingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShortListingResponse>
      PARSER = new com.google.protobuf.AbstractParser<ShortListingResponse>() {
    @Override
    public ShortListingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShortListingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShortListingResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ShortListingResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public ShortListingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

