// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

/**
 * Protobuf type {@code com.group5.proto.Listing.ShortListingResponse}
 */
public final class ShortListingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.group5.proto.Listing.ShortListingResponse)
    ShortListingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShortListingResponse.newBuilder() to construct.
  private ShortListingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShortListingResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShortListingResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShortListingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            price_ = input.readInt64();
            break;
          }
          case 18: {
            ImageFileMessage.Builder subBuilder = null;
            if (image_ != null) {
              subBuilder = image_.toBuilder();
            }
            image_ = input.readMessage(ImageFileMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image_);
              image_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            AddressMessage.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(AddressMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            id_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ShortListingResponse.class, Builder.class);
  }

  public static final int PRICE_FIELD_NUMBER = 1;
  private long price_;
  /**
   * <code>int64 price = 1;</code>
   * @return The price.
   */
  @Override
  public long getPrice() {
    return price_;
  }

  public static final int IMAGE_FIELD_NUMBER = 2;
  private ImageFileMessage image_;
  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   * @return Whether the image field is set.
   */
  @Override
  public boolean hasImage() {
    return image_ != null;
  }
  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   * @return The image.
   */
  @Override
  public ImageFileMessage getImage() {
    return image_ == null ? ImageFileMessage.getDefaultInstance() : image_;
  }
  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   */
  @Override
  public ImageFileMessageOrBuilder getImageOrBuilder() {
    return getImage();
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private AddressMessage address_;
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   * @return Whether the address field is set.
   */
  @Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   * @return The address.
   */
  @Override
  public AddressMessage getAddress() {
    return address_ == null ? AddressMessage.getDefaultInstance() : address_;
  }
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   */
  @Override
  public AddressMessageOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int ID_FIELD_NUMBER = 4;
  private long id_;
  /**
   * <code>int64 id = 4;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (price_ != 0L) {
      output.writeInt64(1, price_);
    }
    if (image_ != null) {
      output.writeMessage(2, getImage());
    }
    if (address_ != null) {
      output.writeMessage(3, getAddress());
    }
    if (id_ != 0L) {
      output.writeInt64(4, id_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (price_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, price_);
    }
    if (image_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getImage());
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAddress());
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ShortListingResponse)) {
      return super.equals(obj);
    }
    ShortListingResponse other = (ShortListingResponse) obj;

    if (getPrice()
        != other.getPrice()) return false;
    if (hasImage() != other.hasImage()) return false;
    if (hasImage()) {
      if (!getImage()
          .equals(other.getImage())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrice());
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ShortListingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ShortListingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShortListingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ShortListingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ShortListingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.group5.proto.Listing.ShortListingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.group5.proto.Listing.ShortListingResponse)
      ShortListingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShortListingResponse.class, Builder.class);
    }

    // Construct using com.group5.proto.Listing.ShortListingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      price_ = 0L;

      if (imageBuilder_ == null) {
        image_ = null;
      } else {
        image_ = null;
        imageBuilder_ = null;
      }
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      id_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Listing.internal_static_com_group5_proto_Listing_ShortListingResponse_descriptor;
    }

    @Override
    public ShortListingResponse getDefaultInstanceForType() {
      return ShortListingResponse.getDefaultInstance();
    }

    @Override
    public ShortListingResponse build() {
      ShortListingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ShortListingResponse buildPartial() {
      ShortListingResponse result = new ShortListingResponse(this);
      result.price_ = price_;
      if (imageBuilder_ == null) {
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ShortListingResponse) {
        return mergeFrom((ShortListingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ShortListingResponse other) {
      if (other == ShortListingResponse.getDefaultInstance()) return this;
      if (other.getPrice() != 0L) {
        setPrice(other.getPrice());
      }
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ShortListingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ShortListingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long price_ ;
    /**
     * <code>int64 price = 1;</code>
     * @return The price.
     */
    @Override
    public long getPrice() {
      return price_;
    }
    /**
     * <code>int64 price = 1;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(long value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 price = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0L;
      onChanged();
      return this;
    }

    private ImageFileMessage image_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ImageFileMessage, ImageFileMessage.Builder, ImageFileMessageOrBuilder> imageBuilder_;
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     * @return Whether the image field is set.
     */
    public boolean hasImage() {
      return imageBuilder_ != null || image_ != null;
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     * @return The image.
     */
    public ImageFileMessage getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? ImageFileMessage.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public Builder setImage(ImageFileMessage value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
        onChanged();
      } else {
        imageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public Builder setImage(
        ImageFileMessage.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
        onChanged();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public Builder mergeImage(ImageFileMessage value) {
      if (imageBuilder_ == null) {
        if (image_ != null) {
          image_ =
            ImageFileMessage.newBuilder(image_).mergeFrom(value).buildPartial();
        } else {
          image_ = value;
        }
        onChanged();
      } else {
        imageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = null;
        onChanged();
      } else {
        image_ = null;
        imageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public ImageFileMessage.Builder getImageBuilder() {
      
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    public ImageFileMessageOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            ImageFileMessage.getDefaultInstance() : image_;
      }
    }
    /**
     * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ImageFileMessage, ImageFileMessage.Builder, ImageFileMessageOrBuilder>
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ImageFileMessage, ImageFileMessage.Builder, ImageFileMessageOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private AddressMessage address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        AddressMessage, AddressMessage.Builder, AddressMessageOrBuilder> addressBuilder_;
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     * @return The address.
     */
    public AddressMessage getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? AddressMessage.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public Builder setAddress(AddressMessage value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public Builder setAddress(
        AddressMessage.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public Builder mergeAddress(AddressMessage value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            AddressMessage.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public AddressMessage.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    public AddressMessageOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            AddressMessage.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AddressMessage, AddressMessage.Builder, AddressMessageOrBuilder>
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AddressMessage, AddressMessage.Builder, AddressMessageOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private long id_ ;
    /**
     * <code>int64 id = 4;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 4;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.group5.proto.Listing.ShortListingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.group5.proto.Listing.ShortListingResponse)
  private static final ShortListingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ShortListingResponse();
  }

  public static ShortListingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShortListingResponse>
      PARSER = new com.google.protobuf.AbstractParser<ShortListingResponse>() {
    @Override
    public ShortListingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShortListingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShortListingResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ShortListingResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public ShortListingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

