// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public interface ShortListingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.group5.proto.Listing.ShortListingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 price = 1;</code>
   * @return The price.
   */
  long getPrice();

  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   * @return The image.
   */
  com.group5.proto.Listing.ImageFileMessage getImage();
  /**
   * <code>.com.group5.proto.Listing.ImageFileMessage image = 2;</code>
   */
  com.group5.proto.Listing.ImageFileMessageOrBuilder getImageOrBuilder();

  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   * @return The address.
   */
  com.group5.proto.Listing.AddressMessage getAddress();
  /**
   * <code>.com.group5.proto.Listing.AddressMessage address = 3;</code>
   */
  com.group5.proto.Listing.AddressMessageOrBuilder getAddressOrBuilder();

  /**
   * <code>int64 id = 4;</code>
   * @return The id.
   */
  long getId();
}
